<script setup lang="ts">
import { computed, ref } from 'vue';
import { Truck, ArrowUpRight, Plus, Minus, Check, Info } from 'lucide-vue-next';
import { PRICING, estimateFleet, breakEvenUnits } from '../model.mjs';
const units = ref(8);
const economicsUnits = ref(14);
const estimate = computed(()=>estimateFleet(units.value));
const pesos = (value: number) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value);
const contribution = PRICING.monthly - PRICING.variable;
const result = computed(()=>economicsUnits.value*contribution-PRICING.fixed);
</script>
<template>
  <div class="calculator">
    <div class="calculator-input"><span class="mono-label">TU FLOTA, TU ESCALA</span><h3>Empieza con un camión.<br>Piensa en toda tu ciudad.</h3><label for="fleet-range">Número de camiones</label><div class="fleet-value"><button class="icon-btn" aria-label="Quitar un camión" :disabled="units<=1" @click="units--"><Minus :size="18"/></button><output for="fleet-range">{{ units.toString().padStart(2,'0') }}<Truck :size="35"/></output><button class="icon-btn" aria-label="Agregar un camión" :disabled="units>=50" @click="units++"><Plus :size="18"/></button></div><input id="fleet-range" v-model.number="units" type="range" min="1" max="50" :style="{'--range-fill':`${(units-1)/49*100}%`}"><div class="range-labels"><span>1 camión</span><span>50 camiones</span></div><p class="price-note"><Info :size="15"/>Estimación basada en el modelo comercial actual. Puede variar según alcance, infraestructura y necesidades de implementación.</p></div>
    <div class="calculator-result" aria-live="polite" aria-atomic="true"><div class="estimate-label"><span>ESTIMACIÓN PARA {{ units }} UNIDADES</span><span>MXN</span></div><div class="price-line"><span>Implementación <small>Pago inicial · {{ pesos(PRICING.implementation) }} / camión</small></span><strong>{{ pesos(estimate.implementation) }}</strong></div><div class="price-line featured"><span>Suscripción mensual <small>{{ pesos(PRICING.monthly) }} / camión al mes</small></span><strong>{{ pesos(estimate.monthly) }}<small>/ mes</small></strong></div><div class="price-line"><span>Suscripción anual <small>12 meses de servicio</small></span><strong>{{ pesos(estimate.annual) }}</strong></div><p><Check :size="15"/>GPS, plataforma y seguimiento en un ecosistema.</p><a class="btn btn-primary full" href="index.html">Implementar en mi municipio <ArrowUpRight :size="18"/></a><small class="quiet">Continúa al acceso de RutaLimpia para conocer la plataforma.</small></div>
  </div>
  <details class="economics"><summary>Detrás del modelo comercial <span>Costos, SaaS y punto de equilibrio <Plus :size="18"/></span></summary><div class="economics-content"><div class="economics-grid"><div><span class="mono-label">DISPOSITIVO</span><h4>{{ pesos(PRICING.manufacturing) }}</h4><p>Costo interno estimado de fabricación. El precio comercial de implementación es <b>{{ pesos(PRICING.implementation) }} por camión</b>.</p></div><div><span class="mono-label">INGRESO RECURRENTE / UNIDAD</span><h4>{{ pesos(PRICING.monthly) }}<small> / mes</small></h4><p>Costo variable estimado: ≈ {{ pesos(PRICING.variable) }} / mes. Contribución: ≈ {{ pesos(contribution) }} / mes (≈ 83%), antes de costos fijos empresariales.</p></div><div><span class="mono-label">EQUILIBRIO OPERATIVO ESTIMADO</span><h4>{{ breakEvenUnits() }} <small>unidades</small></h4><p>Costos fijos actuales: $10,224.50 MXN / mes. Aproximación basada en los supuestos actuales.</p></div></div><div class="break-even"><div><label for="economics-range">Explora el punto de equilibrio: <b>{{ economicsUnits }} unidades</b></label><input id="economics-range" v-model.number="economicsUnits" type="range" min="1" max="24"><div class="truck-counter" aria-hidden="true"><Truck v-for="n in 24" :key="n" :size="21" :class="{active:n<=economicsUnits}"/></div></div><output for="economics-range" :class="{positive:result>=0}"><b>{{ pesos(result) }}</b><span>{{ result>=0?'Contribución cubre costos fijos':'Por debajo del equilibrio' }}</span><small>Resultado mensual estimado, antes de otros gastos e impuestos.</small></output></div></div></details>
</template>
